_dev:
    - !C.project
        name : "beanstalk_console"
        root : "./"
    - !C.version
        file : "src/version.txt"
    - !C.git
        remote : "git@git.mararun.cn:mara/beanstalk_console.git"

